### ISSUE TITLE
Calculator allows way too many operators

### ISSUE THREAD

**Issue by MUMEi-28** [pooperdoop/JS-Calculator#1]
![image](https://github.com/user-attachments/assets/48c5d714-3718-4ee1-86db-d2db73f52841)

It let me press operators like =, -, /, * multiple times in a row, You end up with stuffs like ++++, -----, -/*%%---++//. This should not be allowed since it messes up the calculations

**Comment by samalamanam** [comment]
I have already resolved this issue, but it made some limitations for other features
