### ISSUE TITLE
Once you clicked equals button, you can add periods again

### ISSUE THREAD

**Issue by MUMEi-28** [pooperdoop/JS-Calculator#5]
![image](https://github.com/user-attachments/assets/03aed188-3fa3-4656-af15-7e3030c143d7)

inputs
3.3 + 3 then clicked equals
output was 6.3
then u can press period again

**Comment by samalamanam** [comment]
Fixed the issue. Thanks for noticing such a vital problem, I wouldn't even have thought of checking if I were to debug it as I was very focused on the parenthesis problems I was experiencing before this
